name: Release
on:
  push:
    branches:
      - main
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: corepack enable
      - run: pnpm i
      # we need slip-sockets to be built even if it's not being published, pnpm wont build it if it doesn't need to be published
      - run: cd packages/slip-sockets && pnpm build
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm publish -r
          title: Create Release
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
